AllCops:
  Exclude:
    - 'db/**/*'
    - bin/setup
    - bin/update

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Lint/HandleExceptions:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false
